name: Slitherlinks
description: A port of https://github.com/davidjosepha/slitherlink to dart
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.1

dev_dependencies:
  pedantic: ^1.9.0
